### PR TITLE
Exploring petsc garbage collection

### PR DESCRIPTION
**Pull request by amartinhuertas**
This PR can only be reviewed/accepted after PR #38 

In this PR I have written the methods required to implement "garbage collection" of PETSc objects in the spirit of the comments in issue https://github.com/gridap/GridapPETSc.jl/issues/41. See also `GCTests.jl` for an illustration of the new methods in action

Two important comments:
- We have to decide where in the library/when to call `gridap_petsc_gc()`.  Perhaps we can add a macro that given a function definition statement injects the call to this method to facilitate the task.
- The current solution as implemented in PETSc is only able to manage a very limited of resurrected PETSc objects in the global array of objects to be lazily destroyed until a global point can be ensured. The capacity of this array can be increased using a configuration option during compilation. Indeed, commenting out the call to `gridap_petsc_gc()` in `GCTests.jl`, I finally got the following error message after some iterations:

```
[1]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[1]PETSC ERROR: Petsc has generated inconsistent data
[1]PETSC ERROR: No more room in array, limit 256 
 recompile src/sys/objects/destroy.c with larger value for MAXREGDESOBJS
```
B. Smith was suggesting to use a different array for GCed objects. Perhaps it is related to this limitation (not sure). 

BTW, the solution works. The program does not deadlock, and you can see that the memory does not grow uncontrollably when you call `gridap_petsc_gc()` frequently.

### CODE REVIEW

**Comment by amartinhuertas** [comment]
> Is this implemented in such a way that the native serial runs work as before ?

No. Native serial works now also use lazy destruction of PETSc objects + periodic calls to `gridap_petsc_gc()`. 

I guess that you ask this question as you would like to have truly automated Garbage Collection when running PETSc programs in serial runs, right? I did not give it a though to this ... how complex would it be to have this separate behaviour?

**Comment by amartinhuertas** [comment]
Before merging, we should also reduce the new tests time. It now takes 96 minutes !

**Comment by fverdugo** [comment]
> No. Native serial works now also use lazy destruction of PETSc objects + periodic calls to gridap_petsc_gc().

yes, for native serial runs we want to retain the old behaviour

**Comment by fverdugo** [comment]
Hi @amartinhuertas I have tagged the PR as draft to avoid an accidental merge until we have a way to recover the old behaviour for native serial runs.

**Pull request merged**
