### PR TITLE
Adding mumps petsc functions

### PR DESCRIPTION
**Pull request by amartinhuertas**
Hi @fverdugo,

FYI ... this PR stems from the need to be able to fine-tune MUMPS parameters, e.g., pivoting thresholds, or memory buffers capacity relaxation parameters. I checked that these parameters cannot be set from command line options if one does not explicitly add low level calls to the MUMPS interface.

Along the way, I have identified that it is needed to  defer the calls to the `setup()` method so that one can guarantee that the PC object is in the required state.

### CODE REVIEW

**Comment by amartinhuertas** [comment]
Ok. Tests are now passing. PR ready to review.

**Comment by fverdugo** [comment]
By looking at the failing documentation job, it seems that GridapPETSc does not work anymore with petsc_jll.

 I find very dangerous not to test GridapPETSc with the default installation of petsc since this is 95% of the use cases (at least on laptops)

**Comment by amartinhuertas** [comment]
> By looking at the failing documentation job, it seems that GridapPETSc does not work anymore with petsc_jll.
> I find very dangerous not to test GridapPETSc with the default installation of petsc since this is 95% of the use cases (at least on laptops)

I find it dangerous too.  If we want to leverage MUMPS from GridapPETSc we have to come up with an automatic solution that let us activate/deactivate MUMPs-specific wrappers during the build stage. Do u know how this can be achieved?

**Comment by fverdugo** [comment]
Working on some improvements of this pr draft in #68

**Review by fverdugo — APPROVED** [review]
@amartinhuertas I'll merge this. In a next step we can see what happens with the GH cache action.

**Pull request merged**
