### PR TITLE
Update to gridap v0.15.1

### PR DESCRIPTION
**Pull request by ericneiva**
Hi, @fverdugo, in this PR, I have accommodated `GridapPETSc.jl` to `Gridap.jl` at v0.15.1.

The only pending thing is to set the `DOCUMENTER_KEY` in `gridap/GridapPETSc.jl`.

Please, review and accept the changes whenever you have sometime.

### CODE REVIEW

**Comment by ericneiva** [comment]
Hi, @fverdugo, I have reopened this PR.

The CI workflow runs with ubuntu 18.04 and x64 architectures, only.

Please, review and merge whenever you have some time.
Thanks!

**Review by fverdugo — COMMENTED** [review]
Hi @ericneiva thanks for your PR!

Just a question: the tests do not show any output in the GH Actions. Can you please check that they are executed correctly?

**Comment by ericneiva** [comment]
> Hi @ericneiva thanks for your PR!
> 
> Just a question: the tests do not show any output in the GH Actions. Can you please check that they are executed correctly?

I do not know why the CI output was truncated... I've run again the jobs and you should now see that the tests were carried out.

**Comment by ericneiva** [comment]
> > Hi @ericneiva thanks for your PR!
> > Just a question: the tests do not show any output in the GH Actions. Can you please check that they are executed correctly?
> 
> I do not know why the CI output was truncated... I've run again the jobs and you should now see that the tests were carried out.

Otherwise, you can check it by downloading the log file.

**Pull request merged**
